---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: ex-hcp-karpenter
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-hcp-karpenter
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-hcp-karpenter
  tags:
    karpenter.sh/discovery: ex-hcp-karpenter
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m"]
        - key: "karpenter.k8s.aws/instance-cpu-manufacturer"
          operator: In
          values: ["intel", "amd"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["6"]
        - key: karpenter.k8s.aws/instanckube-family
          operator: NotIn
          values: ["m7i-flex"]
  limits:
    cpu: 240
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
