apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agentpoolaws
  namespace: hcp-agents
spec:
  organization: hashi-demos-apj
  token:
    secretKeyRef:
      name: hcp-operator
      key: token
  name: agentpoolaws
  agentTokens:
    - name: white
    - name: blue
    - name: red
    - name: yellow
    - name: green
  agentDeployment:
    replicas: 0
    spec:
      containers:
        - name: tfc-agent
          image: "public.ecr.aws/v0v7m9q0/tfc-agent-custom:latest"
          resources:
            requests:
              memory: "1024Mi"
  autoscaling:
    minReplicas: 10
    maxReplicas: 10
    cooldownPeriodSeconds: 60